services:
  - type: web
    name: pick-up
    runtime: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
